#!/usr/bin/env bash
# Install Nginx and the init file have only a message

sudo apt update -y
sudo apt install nginx -y
sudo chown -R $USER:$USER /var/www/html/
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
